# -*- coding: iso-8859-1 -*-
#==============================================================================
#                 Copyright (c) 1997-2015 by miControl(R). All rights reserved.
#
# System   : mcTools V1.04.00.00
# Company  : miControl(R)
#
# Date Time: 16.06.2015 14:05:23
#==============================================================================
# Description: This file was generated by mcTools
#==============================================================================

from _pymc_builtins_ import *

if not PYMC:
   SpGp_NodeId(1)
   Sp(0x5000,0, 3)

def InitPars ():
   Sp(0x3004, 0x00, 0)                # DEV_Enable - Disable
   Sp(0x3000, 0x00, 1)                # DEV_Cmd - Clear error
   Sp(0x3000, 0x00, 0x82)             # DEV_Cmd - Default parameter

   Sp(0x3900, 0x00, 1)                # MOTOR_Type
   Sp(0x3911, 0x00, 2)                # MOTOR_Polarity

   Sp(0x3910, 0x00, 4)                # MOTOR_PolN
   Sp(0x3962, 0x00, 200)              # MOTOR_ENC_Resolution

   Sp(0x3901, 0x00, 10000)            # MOTOR_Nn
   Sp(0x3902, 0x00, 24000)            # MOTOR_Un

   Sp(0x3350, 0x00, 2378)             # VEL_Feedback
   Sp(0x3550, 0x00, 274)              # SVEL_Feedback

   Sp(0x3221, 0x00, 30000)            # CURR_LimitMaxPos
   Sp(0x3223, 0x00, 30000)            # CURR_LimitMaxNeg


   Sp(0x3154, 0x00, 241)              # DEV_DoutEnable

   Sp(0x3210, 0x00, 30)               # CURR_Kp
   Sp(0x3211, 0x00, 30)               # CURR_Ki

   Sp(0x3224, 0x03, 5000)             # CURR_DynLimitTime

   Sp(0x3240, 0x00, 5000)             # CURR_Acc_dI
   Sp(0x3241, 0x00, 200)              # CURR_Acc_dT
   Sp(0x3243, 0x00, 200)              # CURR_Dec_dT

   Sp(0x32a0, 0x08, -22)              # USER_PAR_Nr1

   Sp(0x3310, 0x00, 10)               # VEL_Kp
   Sp(0x3311, 0x00, 2)                # VEL_Ki
   Sp(0x3313, 0x00, 5000)             # VEL_ILimit
   Sp(0x3314, 0x00, 1000)             # VEL_Kvff

   Sp(0x3341, 0x00, 1500)             # VEL_Acc_dT
   Sp(0x3343, 0x00, 3000)             # VEL_Dec_dT

   Sp(0x33c0, 0x03, 7)                # VEL_BlockageGuarding_Time

   Sp(0x3510, 0x00, 450)              # SVEL_Kp
   Sp(0x3511, 0x00, 450)              # SVEL_Ki
   Sp(0x3517, 0x00, 2)                # SVEL_KIxR

   Sp(0x3733, 0x00, 10)               # POS_FollowingErrorTime
   Sp(0x373b, 0x00, 10)               # POS_PositionWindowTime

   Sp(0x39a0, 0x00, 1)                # MOTOR_BrakeManagement_Config
   Sp(0x39a0, 0x10, 10)               # MOTOR_BrakeManagement_OffDelay1
   Sp(0x39a0, 0x11, 20)               # MOTOR_BrakeManagement_OffDelay2
   Sp(0x39a0, 0x12, 30)               # MOTOR_BrakeManagement_OnDelay1
   Sp(0x39a0, 0x13, 40)               # MOTOR_BrakeManagement_OnDelay2

InitPars()

#- main loop ------------------------------------------------------------------

while 1:
   pass
