# -*- coding: iso-8859-1 -*-
#==============================================================================
#                  Copyright(c) 1997-2015 by miControl(R). All rights reserved.
#
# System   : mcTools V1.08.00.00
# Company  : miControl(R)
#
# Date Time: 05.08.2015 13:59:57
#==============================================================================
# Description: This file was generated by mcTools
#==============================================================================

from _pymc_builtins_ import *

if not PYMC:
   SpGp_NodeId(127)
   Sp(0x5000,0, 3)

def InitPar ():
   Sp(0x3004, 0x00, 0)                # DEV_Enable - Disable
   Sp(0x3000, 0x00, 0x1)              # DEV_Cmd - Clear error
   Sp(0x3000, 0x00, 0x82)             # DEV_Cmd - Default parameter

   Sp(0x3900, 0x00, 2)                # MOTOR_Type
   Sp(0x3911, 0x00, 0)                # MOTOR_Polarity

   Sp(0x3910, 0x00, 200)              # MOTOR_PolN

   Sp(0x3901, 0x00, 3000)             # MOTOR_Nn
   Sp(0x3902, 0x00, 24000)            # MOTOR_Un

   Sp(0x3350, 0x00, 0x0)              # VEL_Feedback

   Sp(0x3221, 0x00, 10000)            # CURR_LimitMaxPos
   Sp(0x3223, 0x00, 10000)            # CURR_LimitMaxNeg

   Sp(0x3210, 0x00, 682)              # CURR_Kp
   Sp(0x3211, 0x00, 64)               # CURR_Ki
   Sp(0x3214, 0x00, 400)              # PAR_3214.00h
   Sp(0x3215, 0x00, 4000)             # PAR_3215.00h

   Sp(0x3910, 0x01, 256)              # PAR_3910.01h

InitPar()

#- main loop ------------------------------------------------------------------

while 1:
   pass
