# -*- coding: iso-8859-1 -*-
#==============================================================================
#                 Copyright (c) 1997-2015 by miControl(R). All rights reserved.
#
# System   : mcTools V1.04.00.00
# Company  : miControl(R)
#
# Date Time: 19.05.2015 11:38:45
#==============================================================================
# Description: This file was generated by mcTools
#==============================================================================

from _pymc_builtins_ import *

if not PYMC:
   SpGp_NodeId(1)
   Sp(0x5000,0, 3)

def InitPars ():
   Sp(0x3004, 0x00, 0)                # DEV_Enable - Disable
   Sp(0x3000, 0x00, 1)                # DEV_Cmd - Clear error
   Sp(0x3000, 0x00, 0x82)             # DEV_Cmd - Default parameter

   Sp(0x3900, 0x00, 1)                # MOTOR_Type
   Sp(0x3911, 0x00, 2)                # MOTOR_Polarity

   Sp(0x3910, 0x00, 4)                # MOTOR_PolN
   Sp(0x3962, 0x00, 2000)             # MOTOR_ENC_Resolution

   Sp(0x3901, 0x00, 3000)             # MOTOR_Nn
   Sp(0x3902, 0x00, 24000)            # MOTOR_Un

   Sp(0x3350, 0x00, 2378)             # VEL_Feedback
   Sp(0x3550, 0x00, 2378)             # SVEL_Feedback

   Sp(0x3221, 0x00, 2000)             # CURR_LimitMaxPos
   Sp(0x3223, 0x00, 2000)             # CURR_LimitMaxNeg

   Sp(0x3050, 0x00, -304)             # DEV_DinEnable
   Sp(0x3052, 0x00, -305)             # DEV_DinStartStop

   Sp(0x37b2, 0x00, 35)               # POS_HomingMethod
   Sp(0x37b3, 0x00, 200)              # POS_HomingOffset
   Sp(0x37b4, 0x00, 200)              # POS_HomingVelSwitch
   Sp(0x37b4, 0x01, 200)              # POS_HomingVelZero
   Sp(0x37b5, 0x01, 2000)             # POS_HomingDec

InitPars()

#- main loop ------------------------------------------------------------------

while 1:
   pass
