# -*- coding: iso-8859-1 -*-
#==============================================================================
#                 Copyright (c) 1997-2015 by miControl(R). All rights reserved.
#
# System   : mcTools V1.04.00.00
# Company  : miControl(R)
#
# Date Time: 20.05.2015 13:54:10
#==============================================================================
# Description: This file was generated by mcTools
#==============================================================================

from _pymc_builtins_ import *

if not PYMC:
   SpGp_NodeId(1)
   Sp(0x5000,0, 3)

def InitPars ():
   Sp(0x3004, 0x00, 0)                # DEV_Enable - Disable
   Sp(0x3000, 0x00, 1)                # DEV_Cmd - Clear error
   Sp(0x3000, 0x00, 0x82)             # DEV_Cmd - Default parameter

   Sp(0x3900, 0x00, 1)                # MOTOR_Type
   Sp(0x3911, 0x00, 2)                # MOTOR_Polarity

   Sp(0x3910, 0x00, 4)                # MOTOR_PolN
   Sp(0x3962, 0x00, 2000)             # MOTOR_ENC_Resolution

   Sp(0x3901, 0x00, 3000)             # MOTOR_Nn
   Sp(0x3902, 0x00, 32100)            # MOTOR_Un

   Sp(0x3350, 0x00, 2378)             # VEL_Feedback
   Sp(0x3550, 0x00, 2378)             # SVEL_Feedback

   Sp(0x3221, 0x00, 2000)             # CURR_LimitMaxPos
   Sp(0x3223, 0x00, 2000)             # CURR_LimitMaxNeg

   Sp(0x3003, 0x00, 7)                # DEV_Mode


   Sp(0x3200, 0x00, 1200)             # CURR_DesiredValue

   Sp(0x3241, 0x00, 500)              # CURR_Acc_dT
   Sp(0x3243, 0x00, 500)              # CURR_Dec_dT

   Sp(0x3300, 0x00, 2000)             # VEL_DesiredValue

   Sp(0x3311, 0x00, 20)               # VEL_Ki
   Sp(0x3312, 0x00, 10)               # VEL_Kd
   Sp(0x3314, 0x00, 20)               # VEL_Kvff
   Sp(0x3315, 0x00, 5)                # VEL_Kaff

   Sp(0x3341, 0x00, 1500)             # VEL_Acc_dT
   Sp(0x3343, 0x00, 1500)             # VEL_Dec_dT

   Sp(0x33c0, 0x03, 7)                # VEL_BlockageGuarding_Time

   Sp(0x3510, 0x00, 200)              # SVEL_Kp
   Sp(0x3511, 0x00, 50)               # SVEL_Ki
   Sp(0x3517, 0x00, 20)               # SVEL_KIxR

   Sp(0x3733, 0x00, 10)               # POS_FollowingErrorTime
   Sp(0x373b, 0x00, 10)               # POS_PositionWindowTime

   Sp(0x3004, 0x00, 1)                # DEV_Enable

InitPars()

#- main loop ------------------------------------------------------------------

while 1:
   pass
